import { ListProject, ProjectMap } from "@/types/interfaces"

export const listProject: ListProject[] = [
    {
        id: 1,
        slug: "smafarm-platform",
        title: "Smafarm",
        img: 'projects/smafarm/home.png',
        content: 'The project, titled SmaFarm, is aimed at providing a comprehensive solution for livestock management and care. It addresses the market need for digital platforms that support small and medium farmers by resolving their difficulties in marketing livestock and managing care efficiently. SmaFarm acts as a "one-stop care and marketplace" for livestock, ensuring transparency and trust in high-value transactions.'
    },
    {
        id: 2,
        slug: "revobank-backend",
        title: "Revobank",
        img: 'projects/revobank/login.png',
        content: 'The RevoBank project is a backend API developed using NestJS, simulating core digital banking functionalities such as user registration, login, money transfers, and transaction tracking. This project was created as part of a backend development course focusing on modern technologies and clean architecture. The aim is to provide a simple yet functional API that can manage user accounts and transactions in a secure environment.'
    },
    {
        id: 3,
        slug: "dshopper-frontend",
        title: "dShopers",
        img: 'projects/dshopper/Home.png',
        content: 'This project involves the development of a modern e-commerce website, leveraging Next.js technology. The platform is designed to facilitate users in seamlessly browsing, searching, and filtering products across various categories. It enhances the user experience by providing detailed product information and enabling efficient management of a shopping cart. Meanwhile, administrators can maintain product inventory and manage user profiles through a secure dashboard, which ensures protected access via middleware.'
    }
]

export const detailProjects: ProjectMap = {
    1: {
        slug: "smafarm-platform",
        title: "Smafarm Platform",
        img: '/projects/smafarm/home.png',
        mainContent: "The project, titled SmaFarm, is aimed at providing a comprehensive solution for livestock management and care. It addresses the market need for digital platforms that support small and medium farmers by resolving their difficulties in marketing livestock and managing care efficiently. SmaFarm acts as a 'one-stop care and marketplace' for livestock, ensuring transparency and trust in high-value transactions. The primary objectives of this project are to develop a robust platform that facilitates the buying, selling, and care of livestock, ensure transparency in costing transactions through features such as escrow services, and implement a real-time monitoring dashboard that provides users with confidence in managing their livestock. SmaFarm is designed to serve small and medium farmers who face challenges in accessing digital marketing platforms and managing livestock care. It also targets consumers seeking healthy and verified livestock, particularly during festive periods like Idul Adha, as well as investors who are interested in farming opportunities but often struggle to find trustworthy investment platforms.",
        sub1: "Frontend",
        imgs1: ["/projects/smafarm/livestock.png", "/projects/smafarm/shelter.png", "/projects/smafarm/profile.png", "/projects/smafarm/formBuy.png", "/projects/smafarm/dashboardAdmin.png", "/projects/smafarm/dashboard-breeder.png"],
        c1: "For the front-end development, Next.js was utilized due to its server-side rendering capabilities and enhanced performance in loading times. I Designed 15 user-friendly website interfaces with an average render time of 1 second, delivering enhanced user experience and seamless navigation. Conducted thorough testing on frontend using the Jest testing framework, identifying and resolving approximately 3 bugs to improve platform stability and reliability.",
        sub2: "Backend",
        imgs2: ["/projects/smafarm/ERD-Database.png", "/projects/smafarm/apiList.png"],
        c2: "On the back-end, NestJS was chosen for its modular architecture and strong TypeScript support, facilitating scalable and maintainable solutions ideal for a marketplace platform. I Developed 30 backend API endpoints using NestJS, leveraging its modular architecture to ensure efficient data communication and maintainable business logic. Created and managed 13 Supabase database tables and a dedicated data bucket folder for image storage, optimizing data management by using Prisma schemas for structured migrations and SQL prevention. Conducted thorough testing on backend using the Jest testing framework, identifying and resolving approximately 7 bugs to improve platform stability and reliability.",
        finalContent: "The SmaFarm project has successfully established itself as a comprehensive platform for livestock caretaking and trade. With the integration of key features such as real-time monitoring dashboards and transparent cost structures, user engagement has significantly increased. The unique value proposition of offering one-stop care combined with an efficient marketplace has attracted a diverse user base of breeders and buyers. Moving forward, SmaFarm plans to implement several enhancements to further improve platform performance. This includes the development of a real-time notification system to keep users updated on transaction statuses, storage schedules, and offers. Additionally, the integration of automatic payment gateways will streamline financial transactions, making it easier for users to utilize digital payment methods. In-app chat functionality is also on the roadmap to facilitate direct communication between breeders, service providers, and buyers. Lastly, enhancing reporting and analytics capabilities will provide breeders and farmers with better insights into their performance metrics, ultimately fostering trust and service quality."
    },
    2: {
        slug: "revobank-backend",
        title: "Revobank",
        img: '/projects/revobank/login.png',
        mainContent: "The RevoBank project is a backend API developed using NestJS, simulating core digital banking functionalities such as user registration, login, money transfers, and transaction tracking. This project was created as part of a backend development course focusing on modern technologies and clean architecture. The aim is to provide a simple yet functional API that can manage user accounts and transactions in a secure environment. By the end of the project, the primary objectives include achieving a fully operational API that supports essential banking operations, ensuring robust user authentication, and allowing users to manage their accounts effectively. Additional goals include deploying the system successfully and providing seamless access for testing, which can be done using tools such as Postman. The target audience for this API consists primarily of developers and businesses looking to integrate banking functionalities into their applications. Furthermore, individual users such as bank account holders who desire to manage their accounts and transactions will also benefit from using this project. The system serves both admins, who manage user accounts and settings, and regular customers, who utilize the banking features. I undertook a structured approach to achieve the project's goals, focusing on detailed planning and iterative testing to implement all banking functionalities efficiently and securely.",
        sub1: "Backend Implementation",
        imgs1: ["/projects/revobank/erd-database.png", "/projects/revobank/list-api-swagger.png", "/projects/revobank/example-account-api.png"],
        c1: "I used NestJS for the backend due to its ability to handle scalable server-side applications effectively, while leveraging PostgreSQL as the database for its robust data management capabilities and relational design. I developed 18 backend APIs including authentication and transaction processing by implementing password and PIN hashing techniques and access guards, enhancing security measures to protect user data.	Configured response bodies to exclude sensitive data such as passwords and PINs, reducing risk of data leakage and improving user trust. Designed and implemented database schema using Prisma ORM to create 3 secure database tables, ensuring data integrity and efficient platform performance. Conducted automated testing with over 50% coverage on all modules, identifying bugs quickly and ensuring API reliability and security. As the sole developer, I took responsibility for designing and developing all core API endpoints, implementing JWT-based authentication for secure user access, and establishing role-based access control to ensure safe and compliant system interactions.",
        finalContent: "The RevoBank API successfully meets its key functionalities, allowing users to register, log in, manage accounts, and conduct transactions securely. The implementation of JWT-based authentication ensures that user data is protected, leading to a fully operational system that can handle multiple user requests efficiently. To enhance the project’s performance, optimizations in database query efficiency can be implemented, alongside incorporating automated testing to ensure reliability during future updates. Additionally, considering the integration of more advanced features such as user notifications and reporting tools could enrich user interaction and overall efficiency."
    },
    3: {
        slug: "dshopper-frontend",
        title: "dShopers",
        img: '/projects/dshopper/Home.png',
        mainContent: 'This project involves the development of a modern e-commerce website, leveraging Next.js technology. The platform is designed to facilitate users in seamlessly browsing, searching, and filtering products across various categories. It enhances the user experience by providing detailed product information and enabling efficient management of a shopping cart. Meanwhile, administrators can maintain product inventory and manage user profiles through a secure dashboard, which ensures protected access via middleware. The primary goals for this project include creating a user-friendly interface that supports an extensive range of features. These features comprise a comprehensive homepage with highlighted categories, a search-enabled product listing page, and a detailed product page. Additionally, the implementation of the shopping cart includes functionality for quantity updates and a smooth checkout process. It is also crucial to establish a secure authentication system using NextAuth.js, which will facilitate credential-based logins and ensure an appropriate user experience based on roles. The target audience for this e-commerce platform encompasses two main user types: customers and administrators. Customers are individuals looking for a hassle-free online shopping experience, allowing them to view, select, and purchase products easily. Administrators, on the other hand, require comprehensive tools to manage products, including the addition, deletion, and modification of inventory, as well as user management capabilities through restricted access. The project involved extensive planning and execution. Key efforts included designing a user-friendly interface, integrating a secure authentication system, and ensuring a responsive design to provide an optimal shopping experience.',
        sub1: "Frontend Implementation",
        imgs1: ["/projects/dshopper/ShopPage.png", "/projects/dshopper/ProfileCustomer.png", "/projects/dshopper/ListProductAdmin.png", "/projects/dshopper/PageHandleUsers.png"],
        c1: "The front-end was developed using Next.js due to its efficiency in building server-rendered React applications and optimizing performance. The back-end utilized the Fetch API to connect with external REST APIs, allowing for dynamic product data management and seamless user interactions. Additionally, TypeScript ensured type safety, enhancing code quality. I Developed 11 user-facing pages including product listing, detailed product views, and filtering options by utilizing Incremental Static Regeneration (ISR) and API-based filters, achieving page reload times of around 1 second to enhance customer browsing experience. Implemented authentication to secure 5 protected pages, enforcing role-based access control to ensure that restricted pages are accessed only by authorized users. Engineered the frontend with Next.js framework, boosting SEO performance for product listing and home pages to over 85%, leading to improved page visibility and search engine ranking. Established testing protocols using Jest, achieving average test coverage above 50% to monitor and improve frontend application reliability by detecting bugs early. I was instrumental in implementing the shopping cart functionality, enabling features such as item addition, removal, and quantity updates using the Context API for state management. I also contributed to the setup of role-based access controls to ensure secure user experiences tailored to customers and administrators.",
        finalContent: "The final results of the project demonstrated a fully functional e-commerce website, allowing users to effectively browse and purchase products. Key features, including a responsive shopping cart, detailed product pages, and a secure admin dashboard, were successfully implemented. Testing the application showed positive feedback regarding user experience and ease of navigation, while the integration of NextAuth.js ensured secure and seamless authentication. Future improvements could focus on optimizing load times through code-splitting and enhanced caching strategies. Additionally, implementing advanced search algorithms to refine product filtering could further boost user experience. Incorporating analytics tools to gather user behavior data would allow for targeted enhancements based on actual usage patterns, enhancing overall performance and customer satisfaction."
    }
}